baseURL = "https://blogscroll.com/"
languageCode = "en-us"
title = "BlogScroll - Personal Blog & Site Directory"
description = "An open directory of personal sites and blogs, maintained entirely on GitHub."
theme = "directory"

[params]
description = "An open directory of personal sites and blogs, maintained entirely on GitHub."
publishDate = "Sep 2, 2024"

[outputs]
home = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediaType = "application/rss+xml"
